### ISSUE TITLE
Warning in dnsmasq core

### ISSUE THREAD

**Issue by tdashmike** [jacklul/entware-pi-hole#5]
How do I make this warning go away?

`WARNING WARNING in dnsmasq core: using interface lo instead`

I tried setting interface to "lo" but it still comes up.

By the way, I could not get pihole debug to work, it says:

`/opt/bin/pihole: line 309: syntax error: unexpected redirection`

Thank you!

**Comment by jacklul** [comment]
> `WARNING in dnsmasq core: using interface lo instead`

I'm using setup where interface is set to 'lo' and do not get that warning.
Note that if you changed the interface and restarted then the warning will still be there because they are stored in the database.
From what I observed the warning shows up when the daemon can't bind to selected interface and select it automatically.
If the Pi-hole works with that warning showing up then I guess you will have to ignore it.

> `/opt/bin/pihole: line 309: syntax error: unexpected redirection`

Have you tried running **/opt/bin/pihole** using bash instead? This looks like it didn't run through Entware's bash
As per comment when creating new issue - I need some device infos.

**Comment by tdashmike** [comment]
Ok, I figured out how to use the entware bash. I have attached the file. I deleted the warning but it came back the next time I restarted pi-hole. I also had warnings about the ntp port but I disabled them and the warning went away.

pihole_debug.log _Removed_

Please let me know if there is personal into in the log, I glanced it over twice and didn't see anything that stood out.

**Comment by jacklul** [comment]
Does the Pi-hole work with the error showing up?
Back when I tested it either via binding it to br0 or lo then using firmware's dnsmasq to redirect queries I still had that error even though everything was working fine.

The NTP error is expected if you use NTP server in Merlin firmware as Pi-hole also runs it.

Try setting `dns.listeningMode = "SINGLE"` (or LOCAL, ALL) and check if the warning goes away.

**Comment by tdashmike** [comment]
Yes, it works fine. I'm having some issues with SERVFAIL and the DHCP not handing out the DNS address so I'm still monitoring it.

I changed ```dns.listeningMode = "SINGLE"``` and now it gives a different error ```interface eth0 does not currently exist``` and dns basically stopped working. I didn't try ALL since I probably wouldn't run it that way.

I noticed this setting usually says "Respond only on interface lo" but in this setup the "lo" is missing at the end.

![image](https://github.com/user-attachments/assets/5500bb84-ebf4-409f-8b23-574188a98b89)

**Comment by jacklul** [comment]
Pretty sure you gotta set it to listen on br0 interface instead of eth0

Also you definitely do not want Pi-hole to be your DHCP, you want firmware to handle this. I did not test this at all.

The ALL setting might actually not be that dangerous as the firmware is already properly firewalling the outside

**Comment by tdashmike** [comment]
Ok, I tried setting the listening interface to br0 and lo and ```dns.listeningMode = "SINGLE"``` for both of those and the dns does not work. I also tried ```dns.listeningMode = "ALL"``` and the dns works but still gives the ```using interface lo instead``` warning.

![Screenshot 2024-12-16 103232](https://github.com/user-attachments/assets/85f36e16-3618-491c-90db-b515a56308bf)
![Screenshot 2024-12-16 104013](https://github.com/user-attachments/assets/ccdc45e1-7b25-4593-a7c4-4b3b31dd36ca)

**Comment by jacklul** [comment]
Considering the codebase was written for more recent kernel versions Pi-hole might not be able to correctly get interface status, thus producing that warning.

You should settle with whatever setup that makes the DNS work

**Comment by tdashmike** [comment]
How recent is the dev build? Do you plan on keeping it up to date? Thanks for making this package by the way. It makes sense for me to run it on the router itself. The RT-AX88U Pro has 1gb of ram and I'm only using the default blocklist. Don't want to make my life too difficult with all sort of stuff being blocked.

**Comment by jacklul** [comment]
Until Pi-hole v6 is officially released the main package I try to update weekly while the dev package is built daily using latest commit on the upstreams.
Sometimes the patches become broken due to changes on the upstream - I usually fix those within few days.

After v6 release the main package will follow Pi-hole's versioning.
I will probably keep it updated for as long I am also using it myself, or until maintaining it will become more effort than it is now.

My router has 512MB RAM and I have few extra blocklists added and I'm still at ~180MB free, mostly ticked ones from [firebog.net](https://firebog.net).

**Comment by tdashmike** [comment]
Sounds good, thank you. I'm not familiar with this install method on the router. How do I make an update? Thank you.

**Comment by jacklul** [comment]
Updates are handled by opkg update and upgrade commands
